### ISSUE TITLE
SVGZ support

### ISSUE THREAD

**Issue by suhr** [imgbi/img.bi#28]
Subj.

**Comment by komachi** [comment]
Well, seems like there is a problem. Both Firefox and Chrome can generate datauri from svgz file (using mime type `image/svg+xml-compressed`), but can't display it. There is probably a way to decompress it in browser using some JS gzip realizations, like gzip-js, and then upload it like a normal svg file, but it seems redundant for me. So this is probably won't be fixed until at least one popular browser start to understand such datauris, but if you want to give it a try, just add `image/svg+xml-compressed` to `config.json`.
