### ISSUE TITLE
Provide a userscript for the site

### ISSUE THREAD

**Issue by suhr** [imgbi/img.bi#31]
I2P people disable JS because it leaks information. But userscripts can be useful, because they can be audited and user fully controls what is actually executed in the browser.
So, provide a userscript to use img.bi with disabled JS.

**Comment by komachi** [comment]
Yeah, that's planned, but in form of browser extension.

**Comment by suhr** [comment]
> but in form of browser extension
World is not only Chrome and Firefox.

**Comment by komachi** [comment]
There is need to host full html pages locally, otherwise it's not make any sense as server can inject another `<script>`. With userscripts, that will be too hacky for no good reason.

**Comment by komachi** [comment]
Fixed for Firefox for now, check out https://github.com/imgbi/img.bi-firefox/
