### ISSUE TITLE
HTTPS/TLS server issues

### ISSUE THREAD

**Issue by blobgo** [imgbi/img.bi#37]
Okay this has not really something to do with this repo, but however I see that your site "only" scored B in [sslabs test] (https://www.ssllabs.com/ssltest/analyze.html?d=img.bi).
So at least disabling RC4 would be nice and if you can - adding things like [HSTS] (https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) and [HPKP](https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning) would be fantastic of course.

**Comment by komachi** [comment]
Fixed, now it's A+.

**Comment by blobgo** [comment]
WOW that's fast. I wouldn't had imagine this. Even HSTS. :+1: 
Still no HPKP but anyway nice thing!

**Comment by blobgo** [comment]
BTW if you want some instructions how to enable HPKP here you ccan find some nice instructions: https://noncombatant.org/2015/05/01/about-http-public-key-pinning/
