### ISSUE TITLE
Ads?

### ISSUE THREAD

**Issue by blobgo** [imgbi/img.bi#38]
At first nice all ads on your page have to follow this strict guidelines, including the ones for [acceptable ads] (https://adblockplus.org/en/acceptable-ads#criteria) by AdBlockPlus.
However at first there are no ads (even with disabled adblocker I see none), but - although you say you follow ABPs guidelines https://img.bi/partials/ads.html (so just your ads information page) is blocked by ABPs EasyList. (I think because of a generic filter)
So I assume you didn't tried to get on ABPs list of acceptable ads, because you don't display any ads currently.

Or am I wrong? And do you want to make something against the blocking of the ads information page? (E.g. renaming would already solve the issue)

**Comment by komachi** [comment]
Yes, there is no ads currently. I renamed ads.html so it shouldn't be blocked now.

**Comment by blobgo** [comment]
Oh no I just reloaded the site without cache and it's now completely broken. The drag and drop field for putting in pictures is now completely gone.
It seems there is something wrong... :anguished:

So the link (https://img.bi/#ads) isn't working anyway...
ANd I can still access [ads.html] (https://img.bi/partials/ads.html) so it doesn't seem to be renamed...

**Comment by blobgo** [comment]
Okay, I've just tried it and it's working now. :smiley:
