### ISSUE TITLE
Copy to clipboard button issues

### ISSUE THREAD

**Issue by blobgo** [imgbi/img.bi#44]
The copy buttons at the file view doesn't work. That's surely because of the browser restrictions for access to the clipboard.
Additionally I think it is intended that there are some hover/clicking effects, but they aren't working.

So maybe a better thing would be if you could select the link with one click (e.g. by using [user-select] (https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) although this is not standardised).

**Comment by komachi** [comment]
It works only with Flash enabled, this is the only way to copy text in browser. I probably should replace it with simple selection if browser has no flash.

**Comment by blobgo** [comment]
Well.. I have click to play enabled in Firefox 38.0.1.
But I didn't see any click-to-play message of Firefox while viewing the site, so it seems as it would not (trying to) load flash.

**Comment by blobgo** [comment]
Maybe you also like this: https://github.com/zenorocha/clipboard.js

**Comment by zenorocha** [comment]
+1 ;)

**Comment by komachi** [comment]
Fixed.
