### ISSUE TITLE
Direct image links

### ISSUE THREAD

**Issue by Dol-phin** [imgbi/img.bi#47]
Does this website allow linking directly to the image? If that's not possible, Img.bi can never compete with sites like Imgur.

I tried creating a hotlink: AAANmCAIAAAAq13OYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAASdEVYdFNvZnR3YXJlAEdyZWVuc2hvdF5VCAUAAP+HSURBVHhe7P15cyS5tu2J6RPIZLKW1C2zvupus9d9Ta17z6mqnOeByXkmI4JzksmZyZyzqrKmM9zXH1y/tRaAcDLrvPf63zoO2wbbvrEBhwNwMtaKDcT/pU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33qU5/61Kc+9alPfepTn/rUpz71qU996lOf+tSnPvWpT33q

The URL is super-long and the image can't be accessed.

**Comment by komachi** [comment]
It's not possible to create direct links when images are encrypted, there is no cleartext image on server nor server know passwords to decrypt it. That super-long link is the image itself in base64, it created using JS in browser from ciphertext and password, which never transmitted to server.

But there is direct links to ciphertext, it's /download/{id} for image and /download/thumb/{id} for thumb. You can take ciphertext from this links and decrypt it by yourself, check out https://github.com/imgbi/img.bi.js for example.
