### ISSUE TITLE
OpenGraph, Schema, Twitter card

### ISSUE THREAD

**Issue by shtefcs** [imgbi/img.bi#48]
Hi there,

First of all great app, tnx for sharing it with community.

I tested image i uploaded by posting it on reddit. The main thing for that kind of sites, and all other social sites is to fetch thumb from the link. Right now that's not working. Is it able to add OG, Schema, or Twitter Card in head of the page, so any other site can fetch it ?

Peace,

**Comment by komachi** [comment]
No, it's not possible because images are encrypted.
