### ISSUE TITLE
Website https://img.bi/ is down?

### ISSUE THREAD

**Issue by Naereen** [imgbi/img.bi#55]
Hi.

First things first: thanks for the great work you put into img.bi!
I used it regularly from some time, it's awesome.

Is the website https://img.bi/ down? Are you aware of the issue?
I cannot access it (and am not the only one: http://isup.me/https://img.bi/).

Thanks again, and thanks in advance.

**Comment by d9h02f** [comment]
https://github.com/imgbi/img.bi/issues/53

**Comment by k0nsl** [comment]
Yes, still not up/operable. See: https://github.com/imgbi/img.bi/issues/51#issuecomment-306900695

To whoever maintains img.bi:

Do you need web hosting? If so, then I can help in that regard.

**Comment by Naereen** [comment]
@k0nsl I think no one is maintaining this (I haven't receive a reply in 16 months)

If you have access to efficient and free hosting, well the code is here and ready to be deployed!

**Comment by komachi** [comment]
I don't have time for now to maintain img.bi, but I want to restore it back in future (I don't have ETA, but can be a long time as I busy with other projects). I planned some refactoring which greatly improves img.bi (storing json with base64 encoded ciphertext of encrypted datauri is not very space-efficient, so it's the main point of refactor, although it should bring some other features).

@k0nsl Thanks for your hosting offering, I'll certainly write to you when I return to the project.

BTW, I lost access to img.bi domain name and it was registered by someone else.

**Comment by Naereen** [comment]
OK. Good luck in the mean time

**Comment by k0nsl** [comment]
Thanks for the clarification, @komachi, and I am sad to hear you lost the domain.

Yep, just write me and I will be at your disposal! :+1:
